name: Explorer Report Integration
on:
  push:
    branches: ['main']
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: samuelrayment/explorer-release@v1
      with:
        github-token: ${{secrets.AUTH_TOKEN}}
        explorer-endpoint: ${{secrets.EXPLORER_ENDPOINT}}
        secret-key: ${{secrets.EXPLORER_SECRET}}
