name: DORA test release

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    name: Fake Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fake Deployment
        run: echo "1"
